services:
  identityapi:
    image: ${DOCKER_REGISTRY-}identityapi
    build:
      context: .
      dockerfile: IdentityAPI/Dockerfile

  frontend:
    image: ${DOCKER_REGISTRY-}frontend
    build:
      context: ./Frontend
      args:
        ENV: development

  identitydb:
    image: postgres:17.5

  pgadmin:
    image: dpage/pgadmin4

  seq:
    image: datalust/seq
