namespace Identity.Domain.Identity;

/// <summary>
///     Represents a pair of tokens generated by Identity and used by other apps for authentication
/// </summary>
public class TokenPair
{
    /// <summary>
    ///     Gets the short-lived access token of th pair
    /// </summary>
    public string AccessToken { get; set; }

    /// <summary>
    ///     Get the long-lived refresh token of the pair
    /// </summary>
    public string RefreshToken { get; set; }

    /// <summary>
    ///     Initializes a new instance of <see cref="TokenPair" /> with the given tokens
    /// </summary>
    /// <param name="accessToken">The access token of the pair</param>
    /// <param name="refreshToken">The refresh token of the pair</param>
    public TokenPair(string accessToken, string refreshToken)
    {
        AccessToken = accessToken;
        RefreshToken = refreshToken;
    }
}