name: Frontend
on:
  push:
    paths:
      - Frontend/**
      - .github/**
    branches:
      - master
      - feature/*

jobs:
  format:
    name: Static code analysis
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        node-version: [22.x]
    defaults:
      run:
        working-directory: ./Frontend
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          cache-dependency-path: ./Frontend/package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Apply linter
        run: npm run lint