name: Frontend-Deploy

on:
  push:
    tags:
      - frontend-v*.*.*

permissions:
  id-token: write
  contents: read

env:
  IMAGE_NAME: "frontend"
  AZ_REGISTRY: "tikalcontainerregistry.azurecr.io"

jobs:
  deliver:
    name: Deliver docker image
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          lfs: true

      - name: Checkout LFS objects
        run: git lfs checkout

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to the Azure Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.AZ_REGISTRY }}
          username: ${{ secrets.AZ_SP_CLIENT_ID }}
          password: ${{ secrets.AZ_SP_CLIENT_SECRET }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.AZ_REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=match,pattern=frontend-v(.*),group=1

      - name: Build and Push Image
        uses: docker/build-push-action@v5
        with:
          context: ./Frontend
          file: ./Frontend/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
