name: Identity
on:
  push:
    paths:
      - Identity/**
      - Identity.Tests/**
      - .github/**
    branches:
      - master
      - feature/*

env:
  NUGET_PACKAGES: ${{ github.workspace }}/.nuget/packages

jobs:
  format:
    name: Enforce formatting
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        dotnet-version: ["9.0.X"]
        project:
          [
            "Identity/Identity.App",
            "Identity/Identity.Application",
            "Identity/Identity.Domain",
            "Identity/Identity.Infrastructure",
            "Identity/Identity.Presentation",
            "Identity.Tests/Identity.Application.Tests",
            "Identity.Tests/Identity.Integration",
          ]
    env:
      NUGET_PACKAGES: ${{ github.workspace }}/.nuget/packages
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup dotnet ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ matrix.dotnet-version }}
          cache: true
          cache-dependency-path: "./${{ matrix.project }}/packages.lock.json"

      - name: Restore ${{ matrix.project }}
        run: dotnet restore ./${{ matrix.project }} --locked-mode

      - name: Enforce formatting for ${{ matrix.project }}
        run: dotnet format ./${{ matrix.project }} whitespace --verify-no-changes --no-restore

  unit-test:
    name: Run unit tests
    needs: format
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        dotnet-version: ["9.0.X"]
        project: ["Identity.Application.Tests"]
      fail-fast: false
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup dotnet ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ matrix.dotnet-version }}
          cache: true
          cache-dependency-path: ./Identity.Tests/${{ matrix.project }}/packages.lock.json

      - name: Restore ${{ matrix.project }}
        run: dotnet restore ./Identity.Tests/${{ matrix.project }} --locked-mode

      - name: Build ${{ matrix.project }}
        run: dotnet build ./Identity.Tests/${{ matrix.project }} --configuration Release --no-restore

      - name: Test ${{ matrix.project }}
        run: dotnet test ./Identity.Tests/${{ matrix.project }} --collect:"XPlat Code Coverage" --configuration Release --no-build --results-directory "TestResults-${{ matrix.dotnet-version }}" -- DataCollectionRunSettings.DataCollectors.DataCollector.Configuration.Format=opencover

      - name: Upload dotnet test results
        uses: actions/upload-artifact@v4
        with:
          name: unit-test-results-${{ matrix.dotnet-version }}-${{ matrix.project }}
          path: TestResults-${{ matrix.dotnet-version }}
        if: ${{ always() }}

  integration-test:
    name: Run integration tests
    needs: unit-test
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        dotnet-version: ["9.0.X"]
        project: ["Identity.Integration"]
      fail-fast: false
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup dotnet ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ matrix.dotnet-version }}
          cache: true
          cache-dependency-path: ./Identity.Tests/${{ matrix.project }}/packages.lock.json

      - name: Restore ${{ matrix.project }}
        run: dotnet restore ./Identity.Tests/${{ matrix.project }} --locked-mode

      - name: Build ${{ matrix.project }}
        run: dotnet build ./Identity.Tests/${{ matrix.project }} --configuration Release --no-restore

      - name: Test ${{ matrix.project }}
        run: dotnet test ./Identity.Tests/${{ matrix.project }} --collect:"XPlat Code Coverage" --configuration Release --no-build --results-directory "TestResults-${{ matrix.dotnet-version }}" -- DataCollectionRunSettings.DataCollectors.DataCollector.Configuration.Format=opencover
        env:
          Jwt__SigningKey: ${{ secrets.TEST_SIGNING_KEY }}

      - name: Upload dotnet test results
        uses: actions/upload-artifact@v4
        with:
          name: integration-test-results-${{ matrix.dotnet-version }}-${{ matrix.project }}
          path: TestResults-${{ matrix.dotnet-version }}
        if: ${{ always() }}

  sonar:
    name: Sonarqube scan
    needs: integration-test
    runs-on: ubuntu-24.04
    steps:
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: "zulu"

      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Cache SonarQube Cloud packages
        uses: actions/cache@v4
        with:
          path: ~\sonar\cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar

      - name: Cache SonarQube Cloud scanner
        id: cache-sonar-scanner
        uses: actions/cache@v4
        with:
          path: .\.sonar\scanner
          key: ${{ runner.os }}-sonar-scanner
          restore-keys: ${{ runner.os }}-sonar-scanner

      - name: Setup dotnet 9.0.X
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.X
          cache: true
          cache-dependency-path: ./Identity.Tests/Identity.Integration/packages.lock.json

      - name: Install SonarQube Cloud scanner
        if: steps.cache-sonar-scanner.outputs.cache-hit != 'true'
        run: |
          dotnet tool update dotnet-sonarscanner -g

      - name: Begin SonarQube Analysis
        env:
          SONAR_TOKEN: ${{ secrets.IDENTITY_SONAR_TOKEN }}
        run: |
          dotnet-sonarscanner begin /k:"fmahdi09_tikal" /o:"fmahdi09" /d:sonar.token="${{ secrets.IDENTITY_SONAR_TOKEN }}" /d:sonar.host.url="https://sonarcloud.io" /d:sonar.scanner.scanAll=false /d:sonar.cs.opencover.reportsPaths=./TestResults/**/coverage.opencover.xml

      - name: Build Projects
        run: |
          dotnet build ./Identity/Identity.Domain
          dotnet build ./Identity/Identity.Application
          dotnet build ./Identity/Identity.Infrastructure
          dotnet build ./Identity/Identity.Presentation
          dotnet build ./Identity/Identity.App
          dotnet build ./Identity.Tests/Identity.Application.Tests
          dotnet build ./Identity.Tests/Identity.Integration

      - uses: actions/download-artifact@v5
        with:
          path: ./TestResults
          merge-multiple: true

      - name: End SonarQube Analysis
        env:
          SONAR_TOKEN: ${{ secrets.IDENTITY_SONAR_TOKEN }}
        run: |
          dotnet-sonarscanner end /d:sonar.token="${{ secrets.IDENTITY_SONAR_TOKEN }}"
